### ISSUE TITLE
NPC sheets do not work

### ISSUE THREAD

**Issue by NordicS** [jsavko/vagabonds#2]
I cannot open NPC sheet and trying to open it produces error in the console
![error](https://user-images.githubusercontent.com/84878803/120509472-3635aa80-c3d1-11eb-8384-6a1a30d1e635.png)

**Comment by jsavko** [comment]
Which version of foundry are you running and which version of the system?

**Comment by jsavko** [comment]
Thanks for the report! It seems I hadn't created new NPCS since I upgraded the system to 08! How foolish of me! Should be fixed within the hour

**Comment by NordicS** [comment]
It seems that you already found the issues but if it helps I am using 0.8.6 foundry and 0.2.3 Vagabonds system.

**Comment by jsavko** [comment]
Just pushed an update that should resolve the issue

**Comment by jsavko** [comment]
Fixed in 0.2.4

**Comment by DooNotResuscitate** [comment]
This issue is still occurring.
![firefox_2022-01-11_07-21-03](https://user-images.githubusercontent.com/33287665/148941633-38d1e9ed-4853-4b4a-a6f9-3656cd8ea277.png)
